CREATE TYPE inventory_operation_types AS ENUM ('LOAD', 'DOWNLOAD');
CREATE TYPE sales_operation_types AS ENUM ('SALE', 'QUOTATION', 'ORDER');
CREATE TYPE shopping_operation_types AS ENUM ('SHOPPING', 'EXPENSE');

CREATE TABLE public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying NOT NULL,
    description character varying,
    client_id character varying,
    email character varying,
    phone character varying,
    country character varying,
    city character varying,
    address character varying,
    credit_days integer,
    credit_limit double precision,
    discount double precision
);

CREATE TABLE public.inventory_operation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type inventory_operation_types NOT NULL,
    document_no character varying,
    emission_date timestamp,
    description character varying,
    total double precision DEFAULT 0,
    total_net double precision DEFAULT 0,
    total_tax double precision DEFAULT 0,
    user_id bigint,
    total_details integer DEFAULT 0,
    total_amount double precision DEFAULT 0
);

CREATE TABLE public.inventory_operation_details (
    main_id bigint NOT NULL,
    line bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint,
    description_product character varying,
    amount double precision,
    unit integer,
    unitary_cost double precision,
    aliquot double precision,
    total_cost double precision DEFAULT 0,
    total_tax double precision DEFAULT 0,
    total double precision DEFAULT 0
);

CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying NOT NULL,
    description character varying,
    mark character varying,
    model character varying,
    referenc character varying,
    discount double precision,
    status boolean,
    origin character varying,
    buy_tax double precision,
    sale_tax double precision
);

CREATE TABLE public.products_stock (
    product_id bigint NOT NULL,
    unit bigint,
    stock double precision
);

CREATE TABLE public.products_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit character varying,
    product_id bigint,
    cost double precision,
    price double precision,
    UNIQUE (id)
);

CREATE TABLE public.profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying
);

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile bigint,
    code character varying NOT NULL,
    password character varying NOT NULL,
    description character varying,
    email character varying,
    status boolean
);

CREATE TABLE public.sales_operation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type sales_operation_types NOT NULL,
    document_no character varying,
    emission_date timestamp,
    client_id bigint,
    seller character varying,
    credit_days integer,
    description character varying,
    user_id bigint,
    total_amount double precision DEFAULT 0,
    percent_discount double precision DEFAULT 0,
    discount double precision DEFAULT 0,
    total_net double precision DEFAULT 0,
    total_exempt double precision DEFAULT 0,
    total_tax double precision DEFAULT 0,
    total double precision DEFAULT 0,
    credit double precision DEFAULT 0,
    cash double precision DEFAULT 0,
    total_net_cost double precision DEFAULT 0,
    total_tax_cost double precision DEFAULT 0,
    total_cost double precision DEFAULT 0,
    total_count_details double precision DEFAULT 0,
    pending boolean
);

CREATE TABLE public.sales_operation_details (
    main_id bigint NOT NULL,
    line bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint,
    description_product character varying,
    amount double precision,
    unit bigint,
    unitary_cost double precision,
    sale_aliquot double precision,
    buy_aliquot double precision,
    price double precision DEFAULT 0,
    total_net_cost double precision DEFAULT 0,
    total_tax_cost double precision DEFAULT 0,
    total_cost double precision DEFAULT 0,
    percent_discount double precision DEFAULT 0,
    discount double precision DEFAULT 0,
    total_net double precision DEFAULT 0,
    total_tax double precision DEFAULT 0,
    total double precision DEFAULT 0
);

CREATE TABLE public.shopping_operation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type shopping_operation_types NOT NULL,
    document_no character varying,
    emission_date timestamp,
    --provider_code character varying,
    provider_name character varying,
    provider_id character varying,
    provider_address character varying,
    provider_phone character varying,
    credit_days integer,
    expiration_date date,
    description character varying,
    user_id bigint,
    total_amount double precision DEFAULT 0,
    total_count_details double precision DEFAULT 0,
    percent_discount double precision DEFAULT 0,
    discount double precision DEFAULT 0,
    total_net double precision DEFAULT 0,
    total_tax double precision DEFAULT 0,
    total double precision DEFAULT 0,
    credit double precision DEFAULT 0,
    cash double precision DEFAULT 0
);

CREATE TABLE public.shopping_operation_details (
    main_id bigint NOT NULL,
    line bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint,
    description_product character varying,
    amount double precision,
    unit bigint,
    unitary_cost double precision,
    percent_discount double precision DEFAULT 0,
    discount double precision DEFAULT 0,
    total_net double precision DEFAULT 0,
    total_tax double precision DEFAULT 0,
    total double precision DEFAULT 0,
    buy_aliquot double precision
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_profile_fkey FOREIGN KEY (profile) REFERENCES public.profile(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_pkey PRIMARY KEY (product_id, unit);

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_product_unit_fkey FOREIGN KEY (unit) REFERENCES public.products_units(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.products_units
    ADD CONSTRAINT products_units_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.products_units
    ADD CONSTRAINT products_units_pkey PRIMARY KEY (product_id, id);

ALTER TABLE ONLY public.inventory_operation
    ADD CONSTRAINT inventory_operation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.inventory_operation_details
    ADD CONSTRAINT inventory_operation_details_pkey PRIMARY KEY (main_id, line);

ALTER TABLE ONLY public.inventory_operation_details
    ADD CONSTRAINT inventory_operation_details_id_product_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.inventory_operation_details
    ADD CONSTRAINT inventory_operation_details_main_id_fkey FOREIGN KEY (main_id) REFERENCES public.inventory_operation(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.inventory_operation_details
    ADD CONSTRAINT inventory_operation_details_unit_fkey FOREIGN KEY (unit) REFERENCES public.products_units(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_operation
    ADD CONSTRAINT sales_operation_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_operation
    ADD CONSTRAINT sales_operation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_operation_details
    ADD CONSTRAINT sales_operation_details_pkey PRIMARY KEY (main_id, line);

ALTER TABLE ONLY public.sales_operation_details
    ADD CONSTRAINT sales_operation_details_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_operation_details
    ADD CONSTRAINT sales_operation_details_main_id_fkey FOREIGN KEY (main_id) REFERENCES public.sales_operation(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.sales_operation_details
    ADD CONSTRAINT sales_operation_details_unit_fkey FOREIGN KEY (unit) REFERENCES public.products_units(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.shopping_operation
    ADD CONSTRAINT shopping_operation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.shopping_operation_details
    ADD CONSTRAINT shopping_operation_details_pkey PRIMARY KEY (main_id, line);

ALTER TABLE ONLY public.shopping_operation_details
    ADD CONSTRAINT shopping_operation_details_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.shopping_operation_details
    ADD CONSTRAINT shopping_operation_details_main_id_fkey FOREIGN KEY (main_id) REFERENCES public.shopping_operation(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.shopping_operation_details
    ADD CONSTRAINT shopping_operation_details_unit_fkey FOREIGN KEY (unit) REFERENCES public.products_units(id) ON UPDATE CASCADE ON DELETE RESTRICT;
