import z from "zod";

// all of this values commented is generated by API
export const CreateInventoryOperationDetail = z.object({
  code_product: z.string().min(1),
  //description_product: z.string(),
  //referenc: z.string(),
  //mark: z.string(),
  //model: z.string(),
  amount: z.number().min(1),
  unit: z.number().min(1),
  //unitary_cost: z.number().min(0),
  //aliquot: z.number().min(0),
  //total_cost: z.number().min(0),
  //total_tax: z.number().min(0),
  //total: z.number().min(0),
});
